---
sampling_rate: 48000
input_time: 110 #ms 
output_time: 10 #ms
batch_size: 16
max_epochs: 100
patience: 50
train_data:
  - [./data/train_x1.wav, ./data/train_y1.wav]
  - [./data/train_x2.wav, ./data/train_y2.wav]
  - [./data/train_x3.wav, ./data/train_y3.wav]
  - [./data/train_x4.wav, ./data/train_y4.wav]
val_data:
  - [./data/val_x.wav, ./data/val_y.wav]
